name: CI + CD
on: [workflow_dispatch]
  
jobs:
  CICD:
    uses: SrinathBala/central-workflows/.github/workflows/CICD.yml@main
    with:
      DISABLE_STAGE: false
    secrets:
      ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
